[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
setuptools = "^70.2.0"
fake-useragent = "^1.5.1"
aiohttp = { extras = ["speedups"], version = "^3.9.5" }
lxml = "^5.2.2"
beautifulsoup4 = "^4.12.3"
line-bot-sdk = "^3.11.0"
cachetools = "^5.3.3"
asyncache = "^0.3.1"
sanic = "^23.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
