[tool.poetry]
name = "ntpu-student-id-linebot"
version = "1.0.0"
description = "可以查詢北大學生學號及姓名的Line機器人"
authors = ["garyellow <gary20011110@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
line-bot-sdk = "^3.2.0"
cachetools = "^5.3.1"
fastapi = "^0.104.0"
uvicorn = { extras = ["standard"], version = "^0.23.2" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
