# This Action requires setting the following secrets:
#
# - RENDER_API_KEY (create from the Account Settings page)
# - RENDER_SERVICE_ID (the service to create a preview for)
#
# And the following variables:
#
# - REGISTRY (the registry to push the image to, e.g. docker.io)

name: Create Preview

on:
  pull_request:
    types: [opened, reopened]

jobs:
  docker-hub:
    name: PUSH PREVIEW IMAGE TO REGISTRY
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository }}:${{ github.head_ref }}

  render:
    name: CREATE PREVIEW ON RENDER
    runs-on: ubuntu-latest
    needs: docker-hub
    permissions:
      pull-requests: write

    steps:
      - name: Create Render service preview
        uses: fjogeleit/http-request-action@v1
        id: render
        with:
          url: "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/preview"
          bearerToken: ${{ secrets.RENDER_API_KEY }}
          data: '{"imagePath": "${{ vars.REGISTRY }}/${{ github.repository }}:${{ github.head_ref }}"}'

      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Preview is created!

            Your Preview Image url is https://${{ vars.REGISTRY }}/${{ github.repository }}:${{ github.head_ref }}.

            Your [Render](https://render.com) Preview Server URL is ${{ fromJson(steps.render.outputs.response).service.serviceDetails.url }}.

            Follow its progress at https://dashboard.render.com/web/${{ fromJson(steps.render.outputs.response).service.id }}.
