# This Action requires setting the following secrets:
#
# - RENDER_API_KEY (create from the Account Settings page)
# - RENDER_SERVICE_ID (the service to create a preview for)
#
# And the following variables:
#
# - REGISTRY (the registry to push the image to, e.g. docker.io)

name: Create Preview

on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-preview:
    name: CREATE PREVIEW
    uses: ./.github/workflows/update-preview.yml

    permissions:
      contents: read
      packages: write
      pull-requests: write

    secrets:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
