# This Action requires setting the following secrets:
#
# - RENDER_API_KEY (create from the Account Settings page)
# - RENDER_SERVICE_ID (the service to create a preview for)
#
# And the following variables:
#
# - REGISTRY (the registry to push the image to, e.g. docker.io)

name: Create Preview

on:
  pull_request:
    types: [opened, reopened]

jobs:
  prepare:
    name: PREPARE HEAD REF
    runs-on: ubuntu-latest

    steps:
      - name: Generate github.head_ref with underline style
        id: head_ref
        run: echo "head_ref=$(echo ${{ github.head_ref }} | tr / _)" >> $GITHUB_OUTPUT

    outputs:
      head_ref: ${{ steps.head_ref.outputs.head_ref }}

  registry:
    name: PUSH PREVIEW IMAGE TO REGISTRY
    runs-on: ubuntu-latest
    needs: prepare

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.REGISTRY }}/${{ github.repository }}:${{ needs.prepare.outputs.head_ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Delete Untagged Images
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          container: ${{ github.event.repository.name }}
          prune-untagged: true

    outputs:
      head_ref: ${{ needs.prepare.outputs.head_ref }}

  render:
    name: CREATE PREVIEW SERVICE
    runs-on: ubuntu-latest
    needs: registry

    permissions:
      pull-requests: write

    steps:
      - name: Create Render Preview Service
        uses: fjogeleit/http-request-action@v1
        id: render
        with:
          url: https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/preview
          bearerToken: ${{ secrets.RENDER_API_KEY }}
          data: |
            {
              "imagePath": "${{ vars.REGISTRY }}/${{ github.repository }}:${{ needs.registry.outputs.head_ref }}"
            }

      - name: Set Docker Command
        uses: fjogeleit/http-request-action@v1
        with:
          method: PATCH
          url: https://api.render.com/v1/services/${{ fromJson(steps.render.outputs.response).service.id }}
          bearerToken: ${{ secrets.RENDER_API_KEY }}
          data: |
            {
              "serviceDetails":
                {
                  "envSpecificDetails":
                    {
                      "dockerCommand": "sanic app:app --host=0.0.0.0 --port=10000 --debug"
                    }
                }
            }

      - name: Redeploy Render Preview Service
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.render.com/v1/services/${{ fromJson(steps.render.outputs.response).service.id }}/deploys
          bearerToken: ${{ secrets.RENDER_API_KEY }}

      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Preview is created!

            Your Preview Image URL is https://${{ vars.REGISTRY }}/${{ github.repository }}:${{ needs.registry.outputs.head_ref }}.

            Your [Render](https://render.com) Preview Server URL is ${{ fromJson(steps.render.outputs.response).service.serviceDetails.url }}.

            Follow its progress at https://dashboard.render.com/web/${{ fromJson(steps.render.outputs.response).service.id }}.
