name: Delete Preview

on:
  pull_request:
    types: [closed]

jobs:
  delete:
    name: Delete Preview Image
    runs-on: ubuntu-latest

    permissions:
      packages: write
      pull-requests: write

    steps:
      - name: Delete Preview Image
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          container: ${{ github.event.repository.name }}
          prune-tags-regexes: ^${{ github.head_ref }}$

      - name: Add comment to Pull Request
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## Preview is deleted!

            The Preview Image have been deleted.
