# This Action requires setting the following secrets:
#
# - DOCKERHUB_USERNAME
# - DOCKERHUB_ACCESS_TOKEN (create in Docker Hub)
# - RENDER_API_KEY (create from the Account Settings page)
# - RENDER_SERVICE_ID (the service to create a preview for)
#
# And the following variables:
#
# - DOCKERHUB_REPOSITORY (the Docker Hub repository to push to)

name: Delete Preview

on:
  pull_request:
    types: [closed]

jobs:
  docker-hub:
    name: DELETE IMAGE TAG FROM DOCKER HUB
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Delete image tag
        uses: fjogeleit/http-request-action@v1
        id: service
        with:
          url: "https://hub.docker.com/v2/repositories/${{ vars.DOCKERHUB_REPOSITORY }}/tags/${{ github.head_ref }}"
          method: "DELETE"

  render:
    name: DELETE IMAGE TAG FROM DOCKER HUB
    runs-on: ubuntu-latest

    steps:
      - name: Generaten Tags substring(0~8)
        id: tag
        run: echo ::set-output name=service-name::$(echo ${{ github.head_ref }} | cut -c 1-8)

      - name: Get Render Preview services
        uses: fjogeleit/http-request-action@v1
        id: service
        with:
          url: "https://api.render.com/v1/services?type=web_service&limit=1&name=NTPU-ID%20Preview%20${{ steps.tag.outputs.service-name }}"
          method: "GET"
          bearerToken: ${{ secrets.RENDER_API_KEY }}

      - name: Delete Render Preview service
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.render.com/v1/services/${{ fromJson(steps.service.outputs.response)[0].service.id }}"
          method: "DELETE"
          bearerToken: ${{ secrets.RENDER_API_KEY }}
