# This Action requires setting the following secrets:
#
# - RENDER_API_KEY (create from the Account Settings page)
# - RENDER_SERVICE_ID (the service to create a preview for)
#
# And the following variables:
#
# - REGISTRY (the registry to push the image to, e.g. docker.io)

name: Release

on:
  push:
    branches:
      - "master"

jobs:
  ci:
    name: RELEASE IMAGE TO REGISTRY
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository }}:latest

  cd:
    name: DEPLOY TO RENDER
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Deploy to Render
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
          bearerToken: ${{ secrets.RENDER_API_KEY }}
