# This Action requires setting the following secrets:
#
# - DOCKERHUB_TOKEN (create from https://hub.docker.com/settings/security)

name: Release the Latest Version

on:
  push:
    branches:
      - main
    paths:
      - app.py
      - ntpu_linebot/**/*.py
      - pyproject.toml
      - poetry.lock
      - Dockerfile
      - .github/workflows/*.yml

concurrency:
  group: release-latest
  cancel-in-progress: true

jobs:
  release:
    name: Release Latest Image to Registry
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
