# This Action requires setting the following secrets:
#
# - RENDER_API_KEY (create from the Account Settings page)
# - RENDER_SERVICE_ID (the service to create a preview for)
# - DOCKERHUB_TOKEN (create from https://hub.docker.com/settings/security)

name: Release the Latest Version

on:
  push:
    branches:
      - main
    paths:
      - app.py
      - ntpu_linebot/**/*.py
      - pyproject.toml
      - poetry.lock
      - Dockerfile
      - .github/workflows/*.yml

concurrency:
  group: release-latest
  cancel-in-progress: true

jobs:
  release:
    name: RELEASE LATEST IMAGE TO REGISTRY
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  render:
    name: DEPLOY TO RENDER
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Deploy to Render
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
          bearerToken: ${{ secrets.RENDER_API_KEY }}
