# This Action requires setting the following secrets:
#
# - RENDER_API_KEY (create from the Account Settings page)
# - RENDER_SERVICE_ID (the service to create a preview for)
# - DOCKERHUB_TOKEN (create from https://hub.docker.com/settings/security)
#
# And the following variables:
#
# - REGISTRY (the registry to push the image to, e.g. docker.io)

name: Release the Latest Version

on:
  push:
    branches:
      - master

jobs:
  release:
    name: RELEASE LATEST IMAGE TO REGISTRY
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DOCKER HUB
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.repository }}:latest,${{ vars.REGISTRY }}/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  render:
    name: DEPLOY TO RENDER
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Deploy to Render
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
          bearerToken: ${{ secrets.RENDER_API_KEY }}
