# This Action requires setting the following secrets:
#
# - DOCKERHUB_USERNAME
# - DOCKERHUB_ACCESS_TOKEN (create in Docker Hub)
# - RENDER_API_KEY (create from the Account Settings page)
# - RENDER_SERVICE_ID (the service to create a preview for)
#
# And the following variables:
#
# - DOCKERHUB_REPOSITORY (the Docker Hub repository to push to)

name: Update Preview

on:
  pull_request:
    types: [synchronize]
    paths:
      - Dockerfile
      - pyproject.toml
      - poetry.lock
      - app.py
      - src/*

jobs:
  docker-hub:
    name: PUSH PREVIEW TO DOCKER HUB
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_REPOSITORY }}:${{ github.head_ref }}

  render:
    name: UPDATE PREVIEW ON RENDER
    runs-on: ubuntu-latest
    needs: docker-hub
    permissions:
      pull-requests: write

    steps:
      - name: Generaten Tags substring(0~8)
        id: tag
        run: echo ::set-output name=service-name::$(echo ${{ github.head_ref }} | cut -c 1-8)

      - name: Get Render Preview services
        uses: fjogeleit/http-request-action@v1
        id: service
        with:
          url: "https://api.render.com/v1/services?type=web_service&limit=1&name=NTPU-ID%20Preview%20${{ steps.tag.outputs.service-name }}"
          method: "GET"
          bearerToken: ${{ secrets.RENDER_API_KEY }}

      - name: Redeploy Render Preview service
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.render.com/v1/services/${{ fromJson(steps.service.outputs.response)[0].service.id }}/deploys"
          bearerToken: ${{ secrets.RENDER_API_KEY }}

      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Preview Server is updated!

            Your [Render](https://render.com) Preview Server URL is ${{ fromJson(steps.service.outputs.response)[0].service.serviceDetails.url }}.

            Follow its progress at https://dashboard.render.com/web/${{ fromJson(steps.service.outputs.response)[0].service.id }}.
