# This Action requires setting the following secrets:
#
# - RENDER_API_KEY (create from the Account Settings page)
# - RENDER_SERVICE_ID (the service to create a preview for)
#
# And the following variables:
#
# - REGISTRY (the registry to push the image to, e.g. docker.io)

name: Update Preview

on:
  pull_request:
    types: [synchronize]
    paths:
      - Dockerfile
      - pyproject.toml
      - poetry.lock
      - app.py
      - src/*

jobs:
  registry:
    name: PUSH PREVIEW IMAGE TO REGISTRY
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.REGISTRY }}/${{ github.repository }}:${{ github.head_ref }}

  fetch:
    name: FETCH PREVIEW ON RENDER
    runs-on: ubuntu-latest

    outputs:
      response: ${{ steps.service.outputs.response }}

    steps:
      - name: Generaten Tags substring
        id: tag
        run: echo service-name=$(echo ${{ github.head_ref }} | cut -c 1-8) >> $GITHUB_OUTPUT

      - name: Get Render Preview services
        uses: fjogeleit/http-request-action@v1
        id: service
        with:
          url: "https://api.render.com/v1/services?type=web_service&limit=1&name=NTPU-ID%20Preview%20${{ steps.tag.outputs.service-name }}"
          method: "GET"
          bearerToken: ${{ secrets.RENDER_API_KEY }}

  create:
    if: needs.fetch.outputs.response == '[]'
    name: CREATE PREVIEW SERVICE
    runs-on: ubuntu-latest
    needs: [fetch, registry]

    permissions:
      pull-requests: write

    steps:
      - name: Create Render Preview Service
        uses: fjogeleit/http-request-action@v1
        id: render
        with:
          url: "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/preview"
          bearerToken: ${{ secrets.RENDER_API_KEY }}
          data: '{"imagePath": "${{ vars.REGISTRY }}/${{ github.repository }}:${{ github.head_ref }}"}'

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Preview is created!

            Your Preview Image URL is https://${{ vars.REGISTRY }}/${{ github.repository }}:${{ github.head_ref }}.

            Your [Render](https://render.com) Preview Server URL is ${{ fromJson(steps.render.outputs.response).service.serviceDetails.url }}.

            Follow its progress at https://dashboard.render.com/web/${{ fromJson(steps.render.outputs.response).service.id }}.

  update:
    if: needs.fetch.outputs.response != '[]'
    name: UPDATE PREVIEW SERVICE
    runs-on: ubuntu-latest
    needs: [fetch, registry]

    permissions:
      pull-requests: write

    steps:
      - name: Redeploy Render Preview Service
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.render.com/v1/services/${{ fromJson(needs.fetch.outputs.response)[0].service.id }}/deploys"
          bearerToken: ${{ secrets.RENDER_API_KEY }}

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## Preview is updated!

            Your Preview Image URL is https://${{ vars.REGISTRY }}/${{ github.repository }}:${{ github.head_ref }}.

            Your [Render](https://render.com) Preview Server URL is ${{ fromJson(needs.fetch.outputs.response)[0].service.serviceDetails.url }}.

            Follow its progress at https://dashboard.render.com/web/${{ fromJson(needs.fetch.outputs.response)[0].service.id }}.
