name: Upsert Preview

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: preview-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  prepare:
    name: PREPARE HEAD REF
    runs-on: ubuntu-latest

    steps:
      - name: Generate github.head_ref with underline style
        id: head_ref
        run: echo "head_ref=$(echo ${{ github.head_ref }} | tr / _)" >> "$GITHUB_OUTPUT"

    outputs:
      head_ref: ${{ steps.head_ref.outputs.head_ref }}

  upsert:
    name: Push Preview Image to Registry
    runs-on: ubuntu-latest
    needs: prepare

    permissions:
      packages: write
      pull-requests: write

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ needs.prepare.outputs.head_ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Add comment to Pull Request
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## Preview Has Been Created or Updated!

            The Preview Image URL is ghcr.io/${{ github.repository }}:${{ needs.prepare.outputs.head_ref }}.

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations
